dist: bionic
language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get -y install libgsl0-dev
before_script:
  # Set up cgreen
  - git clone https://github.com/sampotter/cgreen
  - cd cgreen; make; sudo make install; cd -
  - sudo ldconfig # ...
  # Set up tetgen
  - unzip tetgen1.6.0.zip
  - cd tetgen1.6.0; make -j; cd -
  - PATH=`pwd`/tetgen1.6.0:$PATH export PATH
script:
  # Build everything and run the unit tests
  - ./quick_build.sh
  - ./quick_test.sh
